set mode Oracle;
INSERT INTO DEF_TEST_TABLE (id, test) VALUES (DEF_TEST_TABLE_SEQ.NEXTVAL, 'ASD');
INSERT INTO DEF_TEST_TABLE (id, test) VALUES (DEF_TEST_TABLE_SEQ.NEXTVAL, 'asdasd');
INSERT INTO DEF_TEST_TABLE (id, test) VALUES (DEF_TEST_TABLE_SEQ.NEXTVAL, 'wewe');