spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jms.JmsAutoConfiguration
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: psxSabeSt0re
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    hibernate:
      ddlauto: none
  flyway:
    enabled: true
    locations: classpath:flyway/
    flyway.url: ${spring.datasource.url}
    flyway.password: ${spring.datasource.username}
    flyway.user: ${spring.datasource.password}
  h2:
    console.enabled: true
  devtools:
    restart:
      enabled: true

management:
  health:
    jms:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

security:
  unauthenticatedEndpoints:
    - /actuator/**
    - /v3/api-docs/**
    - /swagger-ui/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /webjars
    - /apis/**
    - /login

springdoc:
  api-docs:
    path: /apis
    # for swagger ui use http://localhost:8080/swagger-ui/index.html

libs:
  path:

sabe:
  phrase_of_the_day: "Nice to meet you, welcome at Sabe Store!"

remote_retriever:
  destination_folder: ./remote_retriever/tmp
  wait_ms_before_delete: 30000

task_executor:
  core_pool_size: 1
  max_pool_size: 2

logging:
  level:
    root: info
    web: info
    sql: debug
#    org.springframework.boot: DEBUG
#    org.springframework.core.env: DEBUG
#    org.springframework: DEBUG