spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: psxSabeSt0re
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    hibernate:
      ddlauto: none
  flyway:
    enabled: true
    locations: classpath:flyway/
    flyway.url: ${spring.datasource.url}
    flyway.password: ${spring.datasource.username}
    flyway.user: ${spring.datasource.password}
  h2:
    console.enabled: true
  devtools:
    restart:
      enabled: true

springdoc:
  api-docs:
    path: /apis
    # for swagger ui use http://localhost:8080/swagger-ui/index.html



sabe:
  phrase_of_the_day: "Nice to meet you, welcome at Sabe Store!"

logging:
  level:
    root: info
    web: info
    sql: debug