CREATE TABLE USER_ROLE(
    ID number NOT NULL PRIMARY KEY,
    ROLE VARCHAR2(40) NOT NULL UNIQUE
);

create SEQUENCE ROLE_SEQ START WITH 1;

CREATE TABLE SABE_USER(
    ID number NOT NULL PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    SURNAME VARCHAR2(255) NOT NULL,
    MAIL VARCHAR2(255) UNIQUE NOT NULL,
    ROLE_ID NUMBER NOT NULL,
    PASSWORD VARCHAR2(128) NOT NULL,
    AGE NUMBER,
    CONSTRAINT fk_role
            FOREIGN KEY (ROLE_ID) REFERENCES USER_ROLE(ID)
);

create SEQUENCE SABE_USER_SEQ START WITH 1;